version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: searchmmo_nginx
    ports:
      - "80:80"  # Expose only port 80
    volumes:
      # Mount application code (read-only)
      - /volume2/Docker/searchmmo/progam:/var/www/html:ro
      # Mount custom Nginx configuration
      - /volume2/Docker/searchmmo/nginx/config/default.conf:/etc/nginx/conf.d/default.conf:ro
      # (Optional) Mount Nginx log directory
      - /volume2/Docker/searchmmo/nginx/data:/var/log/nginx
    depends_on:
      - php
    networks:
      - searchmmo_net
    restart: unless-stopped

  php:
    build:
      context: .
      dockerfile: Dockerfile-php
    container_name: searchmmo_php
    volumes:
      # Mount application code
      - /volume2/Docker/searchmmo/progam:/var/www/html
    networks:
      - searchmmo_net
    restart: unless-stopped

  mysql:
    image: mysql:latest
    container_name: searchmmo_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: searchmmodb
      MYSQL_USER: searchmmo
      MYSQL_PASSWORD: searchmmo123
    volumes:
      # Mount MySQL data directory
      - /volume2/Docker/searchmmo/mysql/data:/var/lib/mysql
    networks:
      - searchmmo_net
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: searchmmo_redis
    volumes:
      # Mount Redis data directory
      - /volume2/Docker/searchmmo/redis/data:/data
    networks:
      - searchmmo_net
    restart: unless-stopped

networks:
  searchmmo_net:
    driver: bridge
